project_id = "theaknjrmfsyauxxvhmk"

[functions.search-deals]
verify_jwt = true

[functions.classify-transactions]
verify_jwt = false

[functions.enrich-transactions]
verify_jwt = false

[functions.send-feedback]
verify_jwt = false

[functions.generate-partner-recommendations]
verify_jwt = false

[functions.parse-bank-statement-pdf]
verify_jwt = false